### ISSUE TITLE
No progress bar

### ISSUE THREAD

**Issue by Robinlovelace** [r-rust/gifski#1]
Awesome pkg, great to see rust used from within R.

I've just been playing with it and the rust CLI and am v. impressed. However I think it's likely people will set tasks that will take a long time and if there's no progress bar, they'll have no way of knowing whether it's worth waiting or starting again, perhaps with a different input (from `ffmpeg` perhaps).

On the Rust CLI I get a nice progress bar shown below *and* the ability to stop it but from the pkg I'm not sure how to get either and I think both could be useful.

*sh reprex:

```r
cargo install gifski
youtube-dl https://youtu.be/CzxeJlgePV4
ffmpeg -i Riding\ BMX\ in\ Potternewton\ Skatepark,\ Leeds,\ UK-CzxeJlgePV4.mp4 frame%04d.png
gifski frame0*.png --output a.gif
## Frame 22 / 705  ####_....................................................................................................................................................... 32m ^C # cancelled by user
 gifski frame0*.png --fps 5 --output a.gif # try again - warning: output = 200+ MB
Frame 663 / 705  #################################################################################################################################################_......... 41s ^C
# only 30 seconds left!
➜  /tmp 
```

R reprex:

```r
setwd(tempdir())
system("youtube-dl https://youtu.be/CzxeJlgePV4 -o v.mp4")
system("ffmpeg -i v.mp4 frame%04d.png")
f = list.files(pattern = "fram")
g = gifski::gifski(f, gif_file = "g.gif", width = 50, height = 50)
browseURL(g)
```

**Comment by Robinlovelace** [comment]
Result of the second operation (thanks to easy to find width and height args it's less than 10 MB unlike the CLI one I produced which is a 200 MB GIF!

![g](https://user-images.githubusercontent.com/1825120/39661068-c5dca634-5043-11e8-9520-90c4c0e24d25.gif)

**Comment by Robinlovelace** [comment]
Another reprex that's probably better for reproducing (less run time on only firs 4 seconds):

```bash
youtube-dl https://youtu.be/CzxeJlgePV4 -o v.mp4
ffmpeg -i v.mp4 -t 00:00:03 -c copy out.mp4 # note -t flag setting 4 seconds
ffmpeg -i out.mp4 frame%04d.png 
gifski frame0*.png --output al.gif --quality 10 # quality tag to make the output smaller
```

**Comment by Robinlovelace** [comment]
Result!

![a-small](https://user-images.githubusercontent.com/1825120/39661313-534efd66-5047-11e8-8d99-a5597fe160ff.gif)

**Comment by jeroen** [comment]
Somehow I didn't get notified for this issue. I've added a simple progress meter now!

**Comment by Robinlovelace** [comment]
Awesome, thanks for the update. Great to see this progress and I know at least one experience C++ programmer learning Rust who may benefit from your work on this.

Will take it for a spin.

**Comment by Robinlovelace** [comment]
Confirmation: works a dream, awesome fix!

Reprex with another trick (not me this time alas ond only 5 seconds ; ):

```r
system("youtube-dl https://youtu.be/Ry8GLZ2altg -o v.mp4")
system("ffmpeg -i v.mp4 -t 00:00:03 -c copy out.mp4")
system("ffmpeg -i out.mp4 frame%04d.png ")
f = list.files(pattern = "frame")
g = gifski::gifski(f, gif_file = "g.gif", width = 200, height = 200)
```


Frame 47 (52%)

**Comment by Robinlovelace** [comment]
P.s. I've had problems with not being alerted to things - may be due to it being in a team but not sure.

P.s. 2 here's the obligatory gif:

![g](https://user-images.githubusercontent.com/1825120/40085595-ed518d72-5892-11e8-97b1-e8b4787885ba.gif)
