### ISSUE TITLE
`GLIBC_2.27' not found

### ISSUE THREAD

**Issue by sreejyothi** [r-rust/gifski#11]
rustc: /usr/lib/libm.so.6: version `GLIBC_2.27' not found (required by /usr/lib/x86_64-linux-gnu/librustc_driver-77b5a7345ef49dcd.so)
error: could not compile `libc`.

**Comment by jeroen** [comment]
Please make an effort to include more details about the error log, your operating system, version of rust, etc. We cannot reproduce any problem from the above.
