### ISSUE TITLE
Installation error: error: failed to download from `https://crates.io/api/v1/crates/libc/0.2.90/download`

### ISSUE THREAD

**Issue by zavud** [r-rust/gifski#18]
I try to install gifski, but I get the following error:

`> devtools::install_github("r-rust/gifski")
Downloading GitHub repo r-rust/gifski@HEAD
✔  checking for file ‘/tmp/Rtmp7m6ZmX/remotes243a319cbbc/r-rust-gifski-6b86cc6/DESCRIPTION’ (465ms)
─  preparing ‘gifski’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘gifski_1.4.3-1.tar.gz’
   Warning in sprintf(gettext(fmt, domain = domain), ...) :
     one argument not used by format 'invalid uid value replaced by that for user 'nobody''
   Warning: invalid uid value replaced by that for user 'nobody'

Installing package into ‘/home/pokemon/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘gifski’ ...
** using staged installation
cargo 1.57.0
Using /usr/bin/cargo
** libs
gcc -std=gnu99 -I"/home/software/R-4.1.1/lib64/R/include" -DNDEBUG   -I/usr/local/include  -pthread -fvisibility=hidden -fpic  -g -O2  -c wrapper.c -o wrapper.o
PATH="/home/pokemon/.cargo/bin:/home/hi63tov/.cargo/bin:/home/software/R-4.1.1/bin:/home/software/GDAL-2.4.2/bin:/home/software/anaconda3/bin:/home/software/anaconda3/condabin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/miniconda3/bin:/home/software/GAMMA_SOFTWARE-20210701/DISP/bin:/home/software/GAMMA_SOFTWARE-20210701/MSP/bin:/home/software/GAMMA_SOFTWARE-20210701/ISP/bin:/home/software/GAMMA_SOFTWARE-20210701/DIFF/bin:/home/software/GAMMA_SOFTWARE-20210701/LAT/bin:/home/software/GAMMA_SOFTWARE-20210701/IPTA/bin:/home/software/GAMMA_SOFTWARE-20210701/GEO/bin:/home/software/GAMMA_SOFTWARE-20210701/MSP/scripts:/home/software/GAMMA_SOFTWARE-20210701/ISP/scripts:/home/software/GAMMA_SOFTWARE-20210701/DIFF/scripts:/home/software/GAMMA_SOFTWARE-20210701/LAT/scripts:/home/software/GAMMA_SOFTWARE-20210701/IPTA/scripts:/home/pokemon/.local/bin:/home/software/SNAP8/bin:/home/pokemon/.local/bin:/home/pokemon/bin" cargo build --release --manifest-path=myrustlib/Cargo.toml
    Updating crates.io index
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (1 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (1 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (1 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
error: failed to download from `https://crates.io/api/v1/crates/libc/0.2.90/download`

Caused by:
  [56] Failure when receiving data from the peer (Received HTTP code 403 from proxy after CONNECT)
make: *** [myrustlib/target/release/libmyrustlib.a] Error 101
ERROR: compilation failed for package ‘gifski’
* removing ‘/home/pokemon/R/x86_64-pc-linux-gnu-library/4.1/gifski’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp7m6ZmX/file243a15168b18/gifski_1.4.3-1.tar.gz’ had non-zero exit status`

Session info:

`> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /home/software/R-4.1.1/lib64/R/lib/libRblas.so
LAPACK: /home/software/R-4.1.1/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] ps_1.6.0          prettyunits_1.1.1 rprojroot_2.0.2   crayon_1.4.2
 [5] withr_2.4.2       R6_2.5.1          lifecycle_1.0.1   magrittr_2.0.1
 [9] rlang_0.4.12      cachem_1.0.6      cli_3.1.0         curl_4.3.2
[13] remotes_2.4.2     fs_1.5.0          testthat_3.1.0    callr_3.7.0
[17] ellipsis_0.3.2    desc_1.4.0        devtools_2.4.3    tools_4.1.1
[21] glue_1.5.0        purrr_0.3.4       pkgload_1.2.3     fastmap_1.1.0
[25] compiler_4.1.1    processx_3.5.2    pkgbuild_1.3.1    sessioninfo_1.2.2
[29] memoise_2.0.0     usethis_2.1.5`

How can I solve this error? :)

**Comment by jeroen** [comment]
It shows a bunch of network errors. You need a working internet connection to build this package.

**Comment by zavud** [comment]
The problem was solved by setting the proxies with the domain crates.io
