### ISSUE TITLE
Add a 'backward' option

### ISSUE THREAD

**Issue by stla** [r-rust/gifski#26]
Hello,

I think it would  be nice to have a 'backward' option, allowing to record the GIF from frame 1 to frame n to frame 1 (as I did [here](https://laustep.github.io/stlahblog/posts/gifskiBash.html)). It's possible with ImageMagick, but the author of **gifski** doesn't want to add this option (I already asked him).

**Comment by jeroen** [comment]
I don't understand, how is this different from passing `rev(images)` in your input?

**Comment by stla** [comment]
Sorry, I mean forward and backward. I'm not sure this is the same as passing `c(images, rev(images))` because the **gifski** command takes the images in lexicographical order of their names, but maybe the **gifski** package takes the given order of the images?

**Comment by jeroen** [comment]
Yes we just loop over the input images as provided:

https://github.com/r-rust/gifski/blob/850797a1bb5d4536cc79dec278b18ffaba43b95a/src/wrapper.c#L35-L41

**Comment by stla** [comment]
Ok, sorry. Thanks.
