### ISSUE TITLE
segfaults with paths with ~

### ISSUE THREAD

**Issue by jefferis** [r-rust/gifski#5]
Great package @jeroen – have already used it several times. I get a segfault with:

```r
png_path <- file.path(tempdir(), "frame%03d.png")
png(png_path)
par(ask = FALSE)
for(i in 1:10)
  plot(rnorm(i * 10), main = i)
dev.off()
png_files <- sprintf(png_path, 1:10)
gifski(png_files, gif_file="~/Desktop/gifski-segfault.gif")
```

adding something like:

```
gif_file <- normalizePath(gif_file, mustWork = F)
```
[here](https://github.com/r-rust/gifski/blob/4a3c4abf4d9ebdaa399301629ff24d74adac6fa2/R/gifski.R#L32) could protect against this.

**Comment by jeroen** [comment]
Hmm interesting. That would solve the immediate problem, but it should never crash in the first place...
