### ISSUE TITLE
R crashes on Mac with unexpanded path

### ISSUE THREAD

**Issue by thomasp85** [r-rust/gifski#6]
If the output path is not expanded (e.g. '~/Desktop/animation.gif') my R session crashes when creating a gif

**Comment by jeroen** [comment]
Duplicate of https://github.com/r-rust/gifski/issues/5

**Comment by jeroen** [comment]
This should be fixed in the dev version>

**Comment by thomasp85** [comment]
Oh - sorry for the noise
